07-orm/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('questions.urls')),
    path('', include('profiles.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07-orm/profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('signup/', views.CreateUserView.as_view(), name='signup'),
    path('profile/', views.UpdateProfileView.as_view(), name='profile'),
]

07-orm/questions/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'questions'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/', include('questions.api.urls')),
    path('ask/', views.QuestionCreateVeiw.as_view(), name='ask'),
    path('question/<int:qid>', views.AnswerListAndCreate.as_view(), name='question'),
    path('answer/<int:aid>/correct', views.SetCorrect.as_view(), name='set_correct'),
    path('<model>/<int:iid>/<vote>', views.Vote.as_view(), name='vote'),
]

07-orm/templates/include/_header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-between">
<ul class="nav navbar-nav">
  <li class="nav-item active">
	  <h2><a class="nav-link navbar-brend mx-5" href= "{% url 'questions:index' %}"><b>Hasker</b></a></h2>
  </li>
</ul>
    {% include "questions/include/_search.html" %}
<ul class="nav navbar-nav">
  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link btn btn-link" href="{%url 'profiles:profile'%}">{{ user.get_username }}</a>
    </li>
    <li class="nav-item mr-5">
      <a class="nav-link btn btn-link" href="{%url 'profiles:logout'%}">Log out</a>
    </li>
  {% else %}
    <li class="nav-item">
      <a class="nav-link btn btn-link" href="{%url 'profiles:login'%}">Log in</a>
    </li>
    <li class="nav-item mr-5">
      <a class="nav-link btn btn-link" href="{%url 'profiles:signup'%}">Sign up</a>
    </li>
  {%endif %}
</ul>
</nav>

07-orm/templates/include/_pagination.html
{% if is_paginated %}
  <div class="pagination">
      <span class="page-links">
        {% if page_obj.has_previous %}
          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="page-current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
      </span>
    </div>
{% endif %}