07-orm/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('questions.urls')),
    path('', include('profiles.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07-orm/questions/api/urls.py
from django.urls import path, re_path

from rest_framework_simplejwt.views import token_obtain_pair, token_refresh

from .views import QuestionAPIView, QuestionDetailAPIView, AnswerAPIView

urlpatterns = [
    path('v1/questions/', QuestionAPIView.as_view(), name='get_questions'),
    path('v1/questions/<int:pk>', QuestionDetailAPIView.as_view(), name='get_question_detail'),
    path('v1/questions/<int:pk>/answers', AnswerAPIView.as_view(), name='get_answers'),
    path('v1/token/', token_obtain_pair, name='token_obtain'),
    path('v1/token/refresh', token_refresh, name='token_refresh'),
]

07-orm/questions/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'questions'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/', include('questions.api.urls')),
    path('ask/', views.QuestionCreateVeiw.as_view(), name='ask'),
    path('question/<int:qid>', views.AnswerListAndCreate.as_view(), name='question'),
    path('answer/<int:aid>/correct', views.SetCorrect.as_view(), name='set_correct'),
    path('<model>/<int:iid>/<vote>', views.Vote.as_view(), name='vote'),
]

07-orm/questions/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models, transaction
from django.db.models import Sum, Manager
from django.db.models.functions import Coalesce
from django.utils import timezone

from .utils import shift_vote


class WithRatingManager(models.Manager):
    def get_queryset(self):
        q = super().get_queryset()
        return q.annotate(rating=Coalesce(Sum('votes__vote'), 0))

    def by_date(self):
        return self.get_queryset().order_by('-date')

    def by_rating(self):
        return self.get_queryset().order_by('-rating', '-date')


class Authorable(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class VotesMixin:
    """ Add methods to get and set vote
    """
    def get_votes_count(self):
        return self.votes.filter(vote__in=(-1, 1)).count()

    def get_votes_sum(self):
        result = self.votes.aggregate(Sum('vote'))
        return result['vote__sum'] or 0

    def set_vote(self, user, shift_direction):
        self.votes.model.set_vote(self, user, shift_direction)


class Voteable(models.Model):
    """ Abstract class to add vote attribute and related methods
    """
    vote = models.IntegerField(default=0)

    class Meta:
        abstract = True

    @classmethod
    @transaction.atomic
    def set_vote(cls, entity, user, shift_direction):
        v, _ = cls.objects.get_or_create(
            entity=entity,
            author=user,
            defaults={'vote': shift_vote(0, shift_direction)}
        )
        new_vote = shift_vote(v.vote, shift_direction)
        v.vote = new_vote
        v.save()

    @classmethod
    def get_votes(cls, entity):
        result = cls.objects.filter(entity=entity).aggregate(Sum('vote'))
        return result['vote__sum'] or 0


class Tag(models.Model):
    keyword = models.CharField(max_length=30)

    def __str__(self):
        return self.keyword


class Question(Authorable, VotesMixin, models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now, verbose_name='publication date')
    tags = models.ManyToManyField(Tag, blank=True)
    correct_answer = models.OneToOneField(
            'Answer',
            on_delete=models.SET_NULL,
            blank=True, null=True,
            related_name='is_correct_to')

    objects = models.Manager()
    with_rating = WithRatingManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('questions:question', args=[str(self.id)])

    def get_answers_count(self):
        return self.answers.count()

    def add_tags_from_list(self, tag_list):
        for t in tag_list:
            tag, _ = Tag.objects.get_or_create(keyword=t)
            self.tags.add(tag)

    @classmethod
    def create_with_tags(cls, author, title, content, date=timezone.now(), tag_list=[]):
        instance = cls(author=author,
                       title=title,
                       content=content,
                       date=date)
        instance.save()
        instance.add_tags_from_list(tag_list)
        return instance


class Answer(Authorable, VotesMixin, models.Model):
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')

    objects = models.Manager()
    with_rating = WithRatingManager()

    def __str__(self):
        return f"{self.question} - {self.author}"

    @transaction.atomic
    def set_correct(self):
        question = self.question
        question.correct_answer = self
        question.save()

    def is_correct(self):
        return True if self.question.correct_answer == self else False


class AnswerVotes(Voteable, Authorable, models.Model):
    entity = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='votes')


class QuestionVotes(Voteable, Authorable, models.Model):
    entity = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='votes')

07-orm/questions/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Question, Answer


class AnswerCreateForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ('content', 'author', 'question',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['question'].widget = forms.HiddenInput()


class QuestionCreateForm(forms.ModelForm):

    tags_text = forms.CharField(max_length=100)

    class Meta:
        model = Question
        fields = ('title', 'content', )

    def clean_tags_text(self):
        data = self.cleaned_data['tags_text']
        tags = data.split(',')
        if len(tags) > 3:
            raise ValidationError('Maximum 3 tags')
        return tags

07-orm/questions/api/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404

from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import IsAuthenticated

from .serializers import QuestionSerializer, AnswerSerializer
from ..models import Question


class QuestionAPIView(ListAPIView):
    serializer_class = QuestionSerializer
    model = serializer_class.Meta.model
    queryset = Question.objects.all()
    permission_classes = (IsAuthenticated,)

    def get_queryset(self, *args, **kwargs):
        trending = self.request.GET.get('trending')
        if trending:
            queryset = self.model.with_rating.by_rating()
        else:
            queryset = self.model.with_rating.by_date()
        q = self.request.GET.get('q')
        if q:
            q = q.strip()
            if q.startswith('tag:'):
                tag = q[4:]
                queryset = queryset.filter(tags__keyword__icontains=tag)
            else:
                queryset = queryset.filter(Q(title__icontains=q) | Q(content__icontains=q))

        return queryset


class QuestionDetailAPIView(RetrieveAPIView):
    serializer_class = QuestionSerializer
    model = serializer_class.Meta.model
    queryset = model.objects.all()
    permission_classes = (IsAuthenticated,)


class AnswerAPIView(ListAPIView):
    serializer_class = AnswerSerializer
    model = serializer_class.Meta.model
    permission_classes = (IsAuthenticated,)

    def get_queryset(self, *args, **kwargs):
        question_id = self.kwargs[self.lookup_field]
        question = get_object_or_404(Question, pk=question_id)
        return question.answers.all()

07-orm/questions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.views.generic import ListView, CreateView, View
from django.views.generic.edit import BaseFormView
from django.views.generic.list import MultipleObjectMixin, MultipleObjectTemplateResponseMixin
from django.views.generic.list import TemplateResponseMixin
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render, redirect, get_object_or_404

from .forms import QuestionCreateForm, AnswerCreateForm
from .models import Answer, Question


class IndexView(ListView):
    model = Question
    template_name = 'questions/index.html'
    context_object_name = 'question_list'
    queryset = model.with_rating.by_date()
    paginate_by = 20
    extra_context = {'trending_list': Question.with_rating.by_rating}

    def get_queryset(self):
        order = self.request.GET.get('order')
        if order == 'date':
            queryset = self.model.with_rating.by_date()
        elif order == 'rating':
            queryset = self.model.with_rating.by_rating()
        else:
            queryset = super().get_queryset()

        q = self.request.GET.get('q')
        if q:
            q = q.strip()
            if q.startswith('tag:'):
                tag = q[4:]
                queryset = queryset.filter(tags__keyword__icontains=tag)
            else:
                queryset = queryset.filter(Q(title__icontains=q) | Q(content__icontains=q))

        return queryset


class QuestionCreateVeiw(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionCreateForm
    success_url = reverse_lazy('questions:index')
    template_name = 'questions/question_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        obj = form.save()
        obj.add_tags_from_list(form.cleaned_data['tags_text'])
        return super().form_valid(form)


class AnswerListAndCreate(MultipleObjectTemplateResponseMixin,
                          TemplateResponseMixin, MultipleObjectMixin, BaseFormView):
    """ Take positional argument 'qid' with question id
        updates context variable with instance of Question
        and trenging_list
    """
    model = Answer
    form_class = AnswerCreateForm
    paginate_by = 30
    template_name = 'questions/question_detail.html'
    success_url = 'questions:question'

    def get_context_data(self, **kwargs):
        question = get_object_or_404(Question, pk=self.kwargs.get('qid'))
        kwargs['question'] = question
        kwargs['trending_list'] = Question.with_rating.by_rating
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return Answer.with_rating.filter(question=self.kwargs.get('qid')).all()

    def get(self, request, *args, **kwargs):
        """ method copyed from BaseListView to keep pagination"""

        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.") % {
                    'class_name': self.__class__.__name__,
                })
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_initial(self):
        question = get_object_or_404(Question, pk=self.kwargs.get('qid'))
        initial = {'author': self.request.user, 'question': question}
        return initial

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url(), self.kwargs.get('qid'))


class SetCorrect(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        aid = kwargs.get('aid')
        user = request.user
        if aid:
            instance = get_object_or_404(Answer, pk=aid)
            redirect_args = instance.question.id

        else:
            return redirect('questions:index')

        if instance.question.author == user:
            instance.set_correct()
            instance.save()
        return redirect('questions:question', redirect_args)


class Vote(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        instance_id = kwargs.get('iid')
        user = request.user
        action = kwargs.get('vote')
        model = kwargs.get('model')
        if model == 'question':
            instance = get_object_or_404(Question, pk=instance_id)
            redirect_args = instance_id
        elif model == 'answer':
            instance = get_object_or_404(Answer, pk=instance_id)
            redirect_args = instance.question.id

        else:
            return redirect('questions:index')

        instance.set_vote(user, action)
        instance.save()

        return redirect('questions:question', redirect_args)

07-orm/questions/templates/questions/include/_answer_create.html
<div class="row">
  <div class="col-sm-3">
    <h3>Your answer:</h3>
  </div>
  <div class="col-sm-9">
    <form method="post">
      {% csrf_token %} 
      {{ form }} 
      <button type="submit" class="btn btn-primary btn-block">Post answer</button>
    </form>
  </div>
</div><!-- row -->

07-orm/questions/templates/questions/include/_answer_list.html
<ul class="list-group">
{% for answer in answer_list %}
    <li class="list-group-item">
      {% include "questions/include/_answer_list_item.html" %}
    </li>
  {% endfor %} 
</ul>

07-orm/questions/templates/questions/include/_answer_list_item.html
  <div class="row">
    <div class="col-sm-3">
	{% include "questions/include/_vote_arrows.html" with model='answer' instance=answer %}
	<a href="{% url 'questions:set_correct' answer.id %}"
	class="btn btn {% if not user.is_authenticated %}disabled{% endif %}">
	 {% if answer.is_correct %}
	   <i class="far fa-check-square fa-x2"></i>
	 {% else %}
	   <i class="far fa-square fa-x2"></i>
	 {%endif%}
	</a> 
    </div>
    <div class="col-sm-9">
      <p class="text-left">{{ answer.content }}</p>
    </div>
  </div><!-- row -->

07-orm/questions/templates/questions/include/_question_detail_title.html
  <div class="row">
    <div class="col-sm-3">
      {% include "questions/include/_vote_arrows.html" with model='question' instance=question %}
    </div>
    <div class="col-sm-9">
      <p class="text-left"></p>
      <h3>{{ question }}</h3>
    </div>
  </div><!-- row -->

07-orm/questions/templates/questions/include/_question_list.html
<ul class="list-group">
  {% for q in question_list %}
    <li class="list-group-item">
      {% include "questions/include/_question_list_item.html" %}
    </li>
  {% endfor %} 
 </ul>

07-orm/questions/templates/questions/include/_question_list_item.html
<div class="row">
  <div class="col-sm-2">
          <div class="row">
            <div class="col-sm-6">
    		<p class="text-center">{{ q.rating|default_if_none:0 }}</p>
            </div>
            <div class="col-sm-6">
    		<p class="text-center">{{ q.get_answers_count }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
    		<p class="text-center">Votes</p>
            </div>
            <div class="col-sm-6">
    		<p class="text-center">Answers</p>
            </div>
          </div>
  </div>
  <div class="col-sm-6">
          <a class="btn btn" href="{{q.get_absolute_url}}" role="button">{{ q.title }}</a>
          <p class="text-center">{% include "questions/include/_tags.html" %}</p>
  </div>
  <div class="col-sm-4">
    <p class="text-center">{{ q.author }}</p>
    <p class="text-center small align-text-bottom">{{ q.date }}</p>
  </div>
</div>

07-orm/questions/templates/questions/include/_search.html
<form class ="navbar-form navbar-left" action="{% url 'questions:index' %}" method="GET">
  <div class="input-group">
    <input type="text" class="form-control" placeholder="Search" name="q">
    <div class="input-group-btn">
      <button class="btn btn-defualt" type="submit">
	 <i class="glyphicon glyphicon-search"></i>
      </button>
    </div><!-- input-group-btn -->
  </div><!-- form-group -->
</form>

07-orm/questions/templates/questions/include/_sorting_buttons.html
<div class="card border-0">
	<div class="card-body d-flex align-items-center justify-content-around">
      <a class="btn btn-primary" href="{% url 'questions:index' %}" role="button">New Questions</a>
    <a class="btn btn-primary" href=
    "{% url 'questions:index' %}?order=rating" role="button">Hot questions</a>
</div>
</div>

07-orm/questions/templates/questions/include/_tags.html
{% for t in q.tags.all %}
  <a class= "btn btn-info" href="{% url 'questions:index' %}?q=tag:{{t|urlencode}}" role="button">{{ t }}</a>
{% endfor %}

07-orm/questions/templates/questions/include/_trending.html
<div class="card">
  <div class="card-body">
    <p class="text-center"><a class="btn btn-dark btn-lg" href="{% url 'questions:ask' %}" role="button">Ask!</a>
    <h4 class="card-title text-center">Trending</h4>
    <ul class="list-group list-group-flush">
      {% for q in trending_list %}
        {% if q.rating %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <a class="btn btn" href="{{q.get_absolute_url}}" role="button">{{ q.title }}</a>
            <span class="badge badge-pill badge-primary">{{q.rating}}</span>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>

07-orm/questions/templates/questions/include/_vote_arrows.html
<div class="card py-1 my-1 h-auto text-center" style="width: 3rem;">
  <div class="card-header p-0">
    <a href="{% url 'questions:vote' model instance.id 'up' %}" 
    class="btn btn-link {% if not user.is_authenticated %}disabled{% endif %}">
  	<i class="fas fa-arrow-up"></i></a>
  </div>
  <div class="card-body p-0">
    {{ instance.get_votes_sum|default_if_none:0 }}
  </div>
  <div class="card-footer p-0">
    <a href="{% url 'questions:vote' model instance.id 'down' %}"
    class="btn btn-link {% if not user.is_authenticated %}disabled{% endif %}"><i class="fas fa-arrow-down"></i></a>
  </div>
</div>